version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-fastapi-en
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: shatillt
      POSTGRES_PASSWORD: tllitahs
      #DATABASE_URL=postgresql://devuser:devpassword@postgres:5432/devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  fastapi-app:
    build:
      context: .
    volumes:
      # Mount the local app directory to the /code/app directory in the container    
      - ./app:/code/app
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - MODE

volumes:
  postgres_data: